### PR TITLE
New addresses generation script

### PR DESCRIPTION
**Pull request by bartekn**
This script generates SQL update queries to update stellar-api Users database with new network addresses.

We are doing this because stellar-wallet database contains users' public keys.

```
stex run new-addresses
```
```sql
UPDATE Users SET newStellarAddress = "gsanewsiLdJjnnAGScCjbdUN9sWsEzNtBrQSSNWU2BC5NEram6u" WHERE stellarAddress = "gBVjuj5FaqBkniRBN5k1H4X92pPqkHt47";
UPDATE Users SET newStellarAddress = "gs7Hdt8vREaaft1ittLp2QFKWGtamXwo2m8A24T5nTF3Uoay2LX" WHERE stellarAddress = "gf8sX1rMoeokNkjqh35wfrkBA5VMLrDW3Z";
UPDATE Users SET newStellarAddress = "gs88S2zfmjkG4HSaasRtDQed636PqAL5o4KDUNpwQ1KohPR6NFi" WHERE stellarAddress = "gGxnMxUcq4phaAGa14GiGxdXCqmpfaXgLt";
...
```

### CODE REVIEW

**Comment by nullstyle** [comment]
This seems like something that should have a test... at the very least for the public key to new address functionality, given that you aren't using js-stellar-base to perform the translation.

**Comment by nullstyle** [comment]
:+1:

**Comment by bartekn** [comment]
Switched to js-stellar-base and added tests.

**Comment by matschaffer** [comment]
Is there something that covers new signups? Seems like the current process is:

- run new-addresses, save sql
- run resulting sql

What happens if someone signs up between those steps or after the sql has already been applied?

**Comment by matschaffer** [comment]
Just as a point of reference (pulling from the ro database):

```
mysql> select count(*) from wallets_v2;
+----------+
| count(*) |
+----------+
|  3893611 |
+----------+
1 row in set (1 min 41.38 sec)
```

I'm not entirely sure how long this is going to take but drawing from my experience doing the utf8 conversion, I suspect it could take ~6hrs to get all the updates processed.

**Comment by matschaffer** [comment]
I'll start up a snapshot instance so we can try it and find out.

**Comment by matschaffer** [comment]
SQL script creation time from a prod snapshot. Better than expected. Starting update script now to see how that pans out:
```
$ time ./node_modules/.bin/stex run new-addresses > ../updates-prd2.sql

real    31m9.961s
user    20m18.292s
sys     0m34.346s
```

**Comment by matschaffer** [comment]
Metrics from SQL script creation. The high I/O throughput seems like it could have potential for some request timeouts.

screencapture-console-aws-amazon-com-rds-home-1433211957039

**Comment by matschaffer** [comment]
I stopped the update script against the restored test DB after it had been running ~4hrs and was only about 40% through the list.

Going to try dropping the index on that column first to see if we can get this job done a bit more quickly.

**Comment by matschaffer** [comment]
Started a new import at 06:48 UTC that puts this at the start/end of the file:

```
drop index users_new_address_index on Users;
...updates...
create index users_new_address_index on Users (newStellarAddress);
```

**Comment by matschaffer** [comment]
Time for running the update script without indexes, 8.2hrs:

```
mat@i-361cb865|mgmt-001a.prd.stellar001:~/stellar-wallet$ time mysql --defaults-file=prdrestore.my.cnf ix < ../updates-prd2.sql

real    494m24.568s
user    0m50.027s
sys     1m50.727s
```

**Pull request merged**
