### PR TITLE
Add Dockerfile and Makefile

### PR DESCRIPTION
**Pull request by jacekn**

### CODE REVIEW

**Review by brahman81 — APPROVED** [review]
LGTM

**Comment by brahman81** [comment]
checks fail :(

**Comment by jacekn** [comment]
the error is:
```
[12:03:03] Starting 'app'...
Error running initializers!
{ Error: Cannot find module 'sjcl'
    at Function.Module._resolveFilename (module.js:469:15)
```

@vcarl do you know if the error is safe to ignore?

**Comment by vcarl** [comment]
Most likely not safe to ignore, but I don't really know. I can't even install this project locally, even copying exactly the environment travis has. I can dig in and try and force it like I did the other not-yet-dead projects

**Comment by accordeiro** [comment]
I did some digging today, leaving some notes of what I've learned.

I was able to successfully build the project locally, using the following Dockerfile:

```Dockerfile
FROM node:6.9.0

WORKDIR /usr/src/app
COPY . . 
RUN npm install
```

It seems like the problem is with an indirect dependency. `stellar-wallet` depends on [`stellar-lib`](https://github.com/stellar-deprecated/stellar-lib/) (which has been moved to stellar-deprecated), which depends on [`sjcl`](https://github.com/stellar/sjcl-scrypt) (which has been renamed to [`sjcl-scrypt`](https://github.com/stellar/sjcl-scrypt)).

If you look at [`sjcl-scrypt`](https://github.com/stellar/sjcl-scrypt) and the Travis logs, you'll realize that this is potentially the source of the problem – there is a [`require('sjcl');` at the beginning of `index.js`](https://github.com/stellar/sjcl-scrypt/blob/master/index.js#L1), but there is no `sjcl` requirement on `package.json`. So here's my first thought on how to fix the build:

1. Update`sjcl-scrypt` so that it properly exports the module (probably in a different branch so that we don't break anyone who depends on what's on master)
2. Update [`stellar-lib`](https://github.com/stellar-deprecated/stellar-lib/) to point to the updated hash of `sjcl-scrypt` that properly exports itself as a module (this might require removing it from `stellar-deprecated` or at least remove its read-only status) – also probably in a branch so that we don't break anything
3. Update this repo to point to the updated hash of `stellar-lib` that contains the `sjcl-scrypt` fix

I think following these might do the trick. @bartekn I'd love your sanity check here :)

A few other questions:
1. @brahman81 do you think this is worth the effort? At the end of this whole process we might find there are similar issues with other indirect dependencies, and god knows how long it'll take to figure those out.
2. Are we sure we've ever built this project in its latest version and with the current set of dependencies? It seems unlikely to me given the `sjcl` issue.

**Comment by jacekn** [comment]
Thanks @accordeiro for looking into this!

> A few other questions:
> 
>     1. @brahman81 do you think this is worth the effort? At the end of this whole process we might find there are similar issues with other indirect dependencies, and god knows how long it'll take to figure those out.

From my perspective I think we should either fix builds or decommission the service. The reason for that is security issues.
If somebody discovers a significant security vulnerability in one of the libraries we use we'll have to patch and build the code anyway (or decide the decommission the service at short notice)

>     2. Are we sure we've ever built this project in its latest version and with the current set of dependencies? It seems unlikely to me given the `sjcl` issue.

We had a successful build on 7th April 2020 but it was not dockerized build:
https://buildmeister-v2.stellar-ops.com/view/all/job/stellar-wallet/3

It built commit `e9919b5c182236cb965a0bb50e17fa9a4df5eace` which is current master branch

**Comment by vcarl** [comment]
This sounds similar to a fix we had to make on `stellar-api`, which we ultimately did by [vendoring the deprecated dependencies](https://github.com/stellar/stellar-api/pull/119/files) and making some small tweaks to get them working on modern node versions. Same changes might work in here

**Comment by jacekn** [comment]
Closing as we won't be investing time into this service at this point

**Pull request closed without merging**
